name: Rust

on:
 push:
 pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ant_test:
    name: bigBrasileiro - latest
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3      
    - name: Run build    
      run: cd brasileirao-simulator; cargo build --verbose
    - name: Run tests
      run: cd brasileirao-simulator; cargo test -- --nocapture 
